export const SET_STORIES_REQUEST="SET_STORIES_REQUEST";
export const SET_STORIES_SUCCESS="SET_STORIES_SUCCESS";
export const SET_STORIES_FAILURE="SET_STORIES_FAILURE";


export const REMOVE_STORY_REQUEST='REMOVE_STORY_REQUEST'
export const REMOVE_STORY_SUCCESS='REMOVE_STORY_SUCCESS'
export const REMOVE_STORY_FAILURE='REMOVE_STORY_FAILURE'


export const HANDLE_PAGE_REQUEST="HANDLE_PAGE_REQUEST";
export const REMOVE_PAGE_REQUEST="REMOVE_PAGE_REQUEST";

export const SEARCH_REQUEST="SEARCH_REQUEST";
export const SEARCH_SUCCESS="SEARCH_SUCCESS";